# Site settings
title: Leveraged Play
email: info@leveragedplay.com
author:
description:
url:
port: 4321

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
twitter_username: leveragedplay

# Google Analytics
google_analytics: UA-131149070-1
